apiVersion: apps/v1
kind: Deployment
metadata:
  
  labels:
    app: mybackend
  name: mybackend
  namespace: default
  
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mybackend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mybackend
    spec:
      containers:
      - image: CONTAINER_IMAGE
        imagePullPolicy: IfNotPresent
        name: mybackend
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      
      restartPolicy: Always