apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: myclient
  name: myclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myclient
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myclient
    spec:
      containers:
      - image: kaizenvenz/myclient-1.0:1.0
        name: myclient
        resources: {}
status: {}
